name: Run tests


on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.lock
      - name: Run mypy
        run: mypy ./src ./examples

  pyright-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.lock
      - name: Run pyright
        run: pyright ./src ./examples

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.lock
      - name: Run pytest
        run: pytest ./tests
